using System;
using System.Collections.Generic;
using System.Text;

namespace PolarShadow.Core.Aria2RPC
{
    internal class InputFileOption
    {
        public string All_proxy { get; set; }
        public string All_proxy_passwd { get; set; }
        public string All_proxy_user { get; set; }
        public string Allow_overwrite { get; set; }
        public string Allow_piece_length_change { get; set; }
        public string Always_resume { get; set; }
        public string Async_dns { get; set; }
        public string Auto_file_renaming { get; set; }
        public string Bt_enable_hook_after_hash_check { get; set; }
        public string Bt_enable_lpd { get; set; }
        public string Bt_exclude_tracker { get; set; }
        public string Bt_external_ip { get; set; }
        public string Bt_force_encryption { get; set; }
        public string Bt_hash_check_seed { get; set; }
        public string Bt_load_saved_metadata { get; set; }
        public string Bt_max_peers { get; set; }
        public string Bt_metadata_only { get; set; }
        public string Bt_min_crypto_level { get; set; }
        public string Bt_prioritize_piece { get; set; }
        public string Bt_remove_unselected_file { get; set; }
        public string Bt_request_peer_speed_limit { get; set; }
        public string Bt_require_crypto { get; set; }
        public string Bt_save_metadata { get; set; }
        public string Bt_seed_unverified { get; set; }
        public string Bt_stop_timeout { get; set; }
        public string Bt_tracker { get; set; }
        public string Bt_tracker_connect_timeout { get; set; }
        public string Bt_tracker_interval { get; set; }
        public string Bt_tracker_timeout { get; set; }
        public string Check_integrity { get; set; }
        public string Checksum { get; set; }
        public string Conditional_get { get; set; }
        public string Connect_timeout { get; set; }
        public string Content_disposition_default_utf8 { get; set; }
        public string Continue { get; set; }
        public string Dir { get; set; }
        public string Dry_run { get; set; }
        public string Enable_http_keep_alive { get; set; }
        public string Enable_http_pipelining { get; set; }
        public string Enable_mmap { get; set; }
        public string Enable_peer_exchange { get; set; }
        public string File_allocation { get; set; }
        public string Follow_metalink { get; set; }
        public string Follow_torrent { get; set; }
        public string Force_save { get; set; }
        public string Ftp_passwd { get; set; }
        public string Ftp_pasv { get; set; }
        public string Ftp_proxy { get; set; }
        public string Ftp_proxy_passwd { get; set; }
        public string Ftp_proxy_user { get; set; }
        public string Ftp_reuse_connection { get; set; }
        public string Ftp_type { get; set; }
        public string Ftp_user { get; set; }
        public string Gid { get; set; }
        public string Hash_check_only { get; set; }
        public string Header { get; set; }
        public string Http_accept_gzip { get; set; }
        public string Http_auth_challenge { get; set; }
        public string Http_no_cache { get; set; }
        public string Http_passwd { get; set; }
        public string Http_proxy { get; set; }
        public string Http_proxy_passwd { get; set; }
        public string Http_proxy_user { get; set; }
        public string Http_user { get; set; }
        public string Https_proxy { get; set; }
        public string Https_proxy_passwd { get; set; }
        public string Https_proxy_user { get; set; }
        public string Index_out { get; set; }
        public string Lowest_speed_limit { get; set; }
        public string Max_connection_per_server { get; set; }
        public string Max_download_limit { get; set; }
        public string Max_file_not_found { get; set; }
        public string Max_mmap_limit { get; set; }
        public string Max_resume_failure_tries { get; set; }
        public string Max_tries { get; set; }
        public string Max_upload_limit { get; set; }
        public string Metalink_base_uri { get; set; }
        public string Metalink_enable_unique_protocol { get; set; }
        public string Metalink_language { get; set; }
        public string Metalink_location { get; set; }
        public string Metalink_os { get; set; }
        public string Metalink_preferred_protocol { get; set; }
        public string Metalink_version { get; set; }
        public string Min_split_size { get; set; }
        public string No_file_allocation_limit { get; set; }
        public string No_netrc { get; set; }
        public string No_proxy { get; set; }
        public string Out { get; set; }
        public string Parameterized_uri { get; set; }
        public string Pause { get; set; }
        public string Pause_metadata { get; set; }
        public string Piece_length { get; set; }
        public string Proxy_method { get; set; }
        public string Realtime_chunk_checksum { get; set; }
        public string Referer { get; set; }
        public string Remote_time { get; set; }
        public string Remove_control_file { get; set; }
        public string Retry_wait { get; set; }
        public string Reuse_uri { get; set; }
        public string Rpc_save_upload_metadata { get; set; }
        public string Seed_ratio { get; set; }
        public string Seed_time { get; set; }
        public string Select_file { get; set; }
        public string Split { get; set; }
        public string Ssh_host_key_md { get; set; }
        public string Stream_piece_selector { get; set; }
        public string Timeout { get; set; }
        public string Uri_selector { get; set; }
        public string Use_head { get; set; }
        public string User_agent { get; set; }
    }
}
